apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: bss-default-default
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  target:
    name: bss-default-default
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: "10s"
  data:
    - remoteRef:
        key: /minio
        property: accesskey
      secretKey: accessKeyID
    - remoteRef:
        key: /minio
        property: secretkey
      secretKey: secretAccessKey
