apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratix-worker
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: "https://github.com/syntasso/kratix.git"
    path: charts/kratix-worker
    targetRevision: HEAD
    helm:
      values: |
        installFlux: true
        config:
          path: "default/worker-cluster-1"
          namespace: "default"
          secretRef:
            name: bss-default-default
          bucket:
            endpoint: minio.minio.svc.cluster.local:9000
            insecure: true
            bucket: kratix
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kratix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
